image: python:3.12

stages:
  - lint
  - format
  - type_check
  - test
  - security

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt

# -------------------------
# Lint + Quality
# -------------------------
lint:
  stage: lint
  script:
    - pip install ruff flake8 pylint vulture pyupgrade
    - ruff check .
    - flake8 app
    - pylint app
    - vulture app
    - pyupgrade --py312-plus app

# -------------------------
# Format
# -------------------------
format:
  stage: format
  script:
    - pip install black
    - black --check .

# -------------------------
# Type Check
# -------------------------
type_check:
  stage: type_check
  script:
    - pip install mypy
    - mypy app

# -------------------------
# Tests + Coverage
# -------------------------
test:
  stage: test
  script:
    - pip install pytest pytest-cov
    - pytest tests --cov=app --cov-report=term --cov-report=xml

# -------------------------
# Security
# -------------------------
security:
  stage: security
  script:
    - pip install bandit semgrep pip-audit
    - bandit -r app
    - semgrep --config=auto .
    - pip-audit